---
- name: Initial system setup
  hosts: 127.0.0.1
  connection: local
  vars:
    username: felix
  tasks:

  - name: Install basic packages
    apt: pkg="{{ item }}" state=present update_cache=true
    become: true
    with_items:
      - zsh
      - vim
      - nano
      - curl
      - unzip
      - tar
      - wget
      - ntp
      - tmux
      - git
      - build-essential
      - gcc
      - python3.6

  - name: Clone oh-my-zsh
    tags:
      # Suppress warning: [ANSIBLE0006] git used in place of git module
      # Git module doesn't allow us to set `core.autocrlf=input`.
      - skip_ansible_lint
    # core.autocrlf=input prevents https://github.com/robbyrussell/oh-my-zsh/issues/4402
    command: "git clone -c core.autocrlf=input --depth=1 https://github.com/robbyrussell/oh-my-zsh.git ~{{ username }}/.oh-my-zsh"
    args:
      creates: "~{{ username }}/.oh-my-zsh"

  - name: Clone zsh-autosuggestions
    git:
      repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
      dest: "~{{ username }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

  - name: Clone zsh-syntax-highlightling
    git:
      repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
      dest:  "~{{ username }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

  - name: Set default shell
    become: true
    user: name="{{ username }}" shell=/bin/zsh

  - name: Install rustup
    shell: "curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none"
    args:
      creates: "~{{ username }}/.rustup"

  - name: Install Rust stable
    shell: "rustup install stable"

  - name: Install Rust nightly
    shell: "rustup install nightly"

  - name: Update Rust
    shell: "rustup update"

  - name: Install Rust wasm target
    shell: "rustup target add wasm32-unknown-unknown --toolchain nightly"

  - name: Install basic GUI programms
    apt: pkg="{{ item }}" state=present update_cache=true
    become: true
    with_items:
      - firefox
      - thunderbird
      - chromium-browser

  - name: Check if VS Code is installed
    command: dpkg-query -W code
    register: code_deb
    failed_when: code_deb.rc > 1
    changed_when: code_deb.rc == 1

  - name: Download VS Code
    get_url:
      url: "https://go.microsoft.com/fwlink/?LinkID=760868"
      dest: "/tmp/code.deb"
    when: code_deb.rc == 1

  - name: Install VS Code
    apt: deb="/tmp/code.deb"
    become: true
    when: code_deb.rc == 1


  - name: Check if Steam is installed
    command: dpkg-query -W steam
    register: steam_deb
    failed_when: steam_deb.rc > 1
    changed_when: steam_deb.rc == 1

  - name: Download Steam
    get_url:
      url: "https://steamcdn-a.akamaihd.net/client/installer/steam.deb"
      dest: "/tmp/steam.deb"
    when: steam_deb.rc == 1

  - name: Install Steam
    apt: deb="/tmp/steam.deb"
    become: true
    when: steam_deb.rc == 1


  - name: Fix apt dependencies
    shell: "apt-get --fix-broken install"
    become: true
