---
- name: Initial system setup
  hosts: 127.0.0.1
  connection: local
  vars:
    username: felix
  tasks:

  - name: Install basic programms and libraries
    apt: pkg="{{ item }}" state=present update_cache=true
    become: true
    with_items:
      - zsh
      - vim
      - nano
      - curl
      - unzip
      - tar
      - wget
      - ntp
      - tmux
      - git
      - subversion
      - build-essential
      - gcc
      - g++
      - python2.7
      - python3.6
      - python-pip
      - openjdk-8-jdk
      - openjdk-8-jre
      - htop
      - mtr-tiny
      - parted
      - imagemagick
      - ant
      - gradle
      - maven
      - autoconf
      - automake
      - make
      - ruby
      - scala
      - clang
      - clisp
      - cmake
      - cmatrix
      - cowsay
      - cowsay-off
      - docker.io
      - erlang-base
      - ffmpeg
      - findbugs
      - fortunes
      - fortunes-off
      - httpie
      - iftop
      - iotop
      - mono-runtime
      - neofetch
      - nmap
      - tree
      - unzip
      - vagrant
      - valgrind
      - avra
      - avrdude
      - avr-libc
      - binutils-avr
      - gcc-avr
      - libssl-dev
      - pkg-config
      - cmake
      - zlib1g-dev
      - command-not-found
      - fonts-lmodern
      - fonts-open-sans


  - name: Clone oh-my-zsh
    tags:
      # Suppress warning: [ANSIBLE0006] git used in place of git module
      # Git module doesn't allow us to set `core.autocrlf=input`.
      - skip_ansible_lint
    # core.autocrlf=input prevents https://github.com/robbyrussell/oh-my-zsh/issues/4402
    command: "git clone -c core.autocrlf=input --depth=1 https://github.com/robbyrussell/oh-my-zsh.git ~{{ username }}/.oh-my-zsh"
    args:
      creates: "~{{ username }}/.oh-my-zsh"

  - name: Clone zsh-autosuggestions
    git:
      repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
      dest: "~{{ username }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

  - name: Clone zsh-syntax-highlightling
    git:
      repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
      dest:  "~{{ username }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

  - name: Set default shell
    become: true
    user: name="{{ username }}" shell=/bin/zsh


  - name: Install rustup
    shell: "curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none"
    args:
      creates: "~{{ username }}/.rustup"

  - name: Install Rust stable
    shell: "rustup install stable"

  - name: Install Rust nightly
    shell: "rustup install nightly"

  - name: Install Rust wasm target
    shell: "rustup target add wasm32-unknown-unknown --toolchain nightly"

  - name: Install Rust components
    shell: "rustup component add {{ item}}"
    with_items:
       - rls-preview
       - rust-analysis
       - rust-src
       - rustfmt-preview

  - name: Update Rust
    shell: "rustup update"

  # This compiles from source and can take some time
  - name: Install cargo programms
    shell: "cargo install {{ item }}"
    args:
      creates: "~{{ username }}/.cargo/bin/{{item}}"
    with_items:
      - cargo-add
      - cargo-audit
      - cargo-deb
      - cargo-profiler
      - comment-strip
      - exa
      - racer
      - xargo

  # This compiles from source and can take some time
  - name: Install cargo tarpaulin
    shell: 'RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin'
    args:
      creates: "~{{ username }}/.cargo/bin/cargo-tarpaulin"


  - name: Fix user groups for docker and ttys
    become: true
    user:
      name: "{{ username }}"
      groups:
        - docker
        - dialout
      append: true


  - name: Install docker-compose
    get_url:
      url: "https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64"
      dest: "/usr/local/bin/docker-compose"
      force: false
      mode: 0755
    become: true


  - name: Clone nvm
    git:
      repo: "https://github.com/creationix/nvm.git"
      dest:  "~{{ username }}/.nvm/"

  - name: Install node latest lts
    shell: 'export NVM_DIR="$HOME/.nvm"; echo "NVM_DIR: $NVM_DIR"; [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"; echo "NVM LOADED"; nvm install 8 --lts --latest-npm --no-progress;'

  - name: Add yarn apt key
    apt_key:
      url: "https://dl.yarnpkg.com/debian/pubkey.gpg"
    become: true

  - name: Add yarn repo list
    copy:
      content: "deb https://dl.yarnpkg.com/debian/ stable main"
      dest: /etc/apt/sources.list.d/yarn.list
    become: true

  - name: Install yarn
    apt:
      pkg: "yarn"
      state: present
      update_cache: true
      install_recommends: false
    become: true


  - name: Create font directory
    file:
      path: "~{{ username }}/.local/share/fonts"
      state: directory
      mode: 0755

  - name: Install Fira Code font
    get_url:
      url: "https://github.com/tonsky/FiraCode/blob/master/distr/ttf/FiraCode-{{ item }}.ttf?raw=true"
      dest: "~{{ username }}/.local/share/fonts/FiraCode-{{ item }}.ttf"
      force: false
    with_items:
      - Bold
      - Light
      - Medium
      - Regular
      - Retina


  - name: Install Source Code Pro
    get_url:
      url: "https://github.com/adobe-fonts/source-code-pro/releases/download/variable-fonts/SourceCodeVariable-{{ item }}.ttf"
      dest: "~{{ username }}/.local/share/fonts/SourceCodeVariable-{{ item }}.ttf"
      force: false
    with_items:
      - Roman
      - Italic

  - name: Update font cache
    shell: "fc-cache -f"
    become: true


  - name: Install basic GUI programms
    apt: pkg="{{ item }}" state=present update_cache=true
    become: true
    with_items:
      - firefox
      - thunderbird
      - chromium-browser
      - pinta
      - gimp
      - inkscape
      - transmission
      - transmission-cli
      - zenmap
      - filezilla
      - darktable
      - wine1.6
      - winetricks
      - playonlinux
      - netbeans
      - gparted
      - vlc
      - wireshark
      - deja-dup
      - libreoffice


  - name: Check if VS Code is installed
    command: dpkg-query -W code
    register: code_deb
    failed_when: code_deb.rc > 1
    changed_when: code_deb.rc == 1

  - name: Download VS Code
    get_url:
      url: "https://go.microsoft.com/fwlink/?LinkID=760868"
      dest: "/tmp/code.deb"
    when: code_deb.rc == 1

  - name: Install VS Code
    apt: deb="/tmp/code.deb"
    become: true
    when: code_deb.rc == 1


  - name: Check if Gitkraken is installed
    command: dpkg-query -W gitkraken
    register: gitkraken_deb
    failed_when: gitkraken_deb.rc > 1
    changed_when: gitkraken_deb.rc == 1

  - name: Download Gitkraken
    get_url:
      url: "https://release.gitkraken.com/linux/gitkraken-amd64.deb"
      dest: "/tmp/gitkraken.deb"
    when: gitkraken_deb.rc == 1

  - name: Install Gitkraken
    apt: deb="/tmp/gitkraken.deb"
    become: true
    when: gitkraken_deb.rc == 1


  - name: Check if Steam is installed
    command: dpkg-query -W steam
    register: steam_deb
    failed_when: steam_deb.rc > 1
    changed_when: steam_deb.rc == 1

  - name: Download Steam
    get_url:
      url: "https://steamcdn-a.akamaihd.net/client/installer/steam.deb"
      dest: "/tmp/steam.deb"
    when: steam_deb.rc == 1

  - name: Install Steam
    apt: deb="/tmp/steam.deb"
    become: true
    when: steam_deb.rc == 1


  - name: Fix apt dependencies
    shell: "apt-get --fix-broken install"
    become: true

