---
- name: Initial system setup
  hosts: 127.0.0.1
  connection: local
  vars:
    home: "/home/felix"
  tasks:
  - name: Install basic packages
    apt: pkg="{{ item }}" state=present update_cache=true
    become: true
    with_items:
      - zsh
      - vim
      - nano
      - curl
      - unzip
      - tar
      - wget
      - ntp
      - tmux
      - git
      - build-essential
  - name: Get dotfiles from GtiHub
    git:
      repo: git@github.com:xosplicer/dotfiles.git
      dest: "{{ home }}" 

